[package]
name = "dpc-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
dpc-common = { path = "../dpc-common" }
clap = { version = "4.5", features = ["derive"] }
concolor = { version = "0.1.1", features = ["api"] }
ariadne = { version = "0.5.0", features = ["auto-color"] }
